<?php /** @var $block Magento\Catalog\Block\Product\View */ ?>
<?php $product = $block->getProduct(); ?>
<script>
    requirejs(['jquery', 'jquery/ui'], function ($) {
        $('#product-addtocart-button').on('click', function () {
            fbq('track', 'AddToCart', {
                "value": '<?= $product->getFinalPrice() ?>',
                "currency": "EUR",
                "content_ids": '<?= $product->getSku() ?>',
                "content_name": '<?= htmlentities($product->getName()) ?>',
                "content_type": 'product',
            });
        });
    });
</script>
