<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 * @var $_helper Spirit\FacebookPixel\ViewModel\Config
 */
$_helper = $block->getData('config');
?>
<?php if ($_helper->getIsActive() && $_helper->getIsAddToCartListActive()): ?>
    <?php $product_selector = $_helper->getAddToCartListProductSelector(); ?>
    <?php $add_to_cart_selector = $_helper->getAddToCartListProductSelector(); ?>
    <script>
        requirejs(['jquery', 'jquery/ui'], function ($) {
            $('<?= /* @noEscape */ $product_selector . ' ' . $add_to_cart_selector ?>').on('click', function () {
                const productElement = $(this).closest('<?= /* @noEscape */ $product_selector ?>')
                const priceElement = $(productElement).find('[data-price-type="finalPrice"]')
                const product_id = $(productElement).find('[data-product-id]').attr('data-product-id')
                const price = $(priceElement).attr('data-price-amount')
                if (price) {
                    fbq('track', 'AddToCart', {
                        "currency": "EUR",
                        "value": price,
                        "content_ids": product_id,
                        "content_type": 'product',
                    });
                }
            });
        });
    </script>
<?php endif; ?>
