<?php
/**
 * @var $block Magento\Framework\View\Element\Template
 * @var $_helper Spirit\FacebookPixel\ViewModel\Config
 */
$_helper = $block->getData('config');
?>
<?php if ($_helper->getIsActive()): ?>
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '<?= /* @noEscape */ $_helper->getPixelID() ?>');
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" style="display:none"
             src="https://www.facebook.com/tr?id=<?= /* @noEscape */
                $_helper->getPixelID() ?>&ev=PageView&noscript=1"
        />
    </noscript>
<?php else: ?>
    <script>
        console.log('No facebook pixel ID is configured');
        console.log('Please check your settings at Stores -> Configuration -> Spirit -> Facebook Pixel');
    </script>
<?php endif; ?>
