<?php
/**
 * @var $block Magento\Checkout\Block\Cart
 * @var $_helper Spirit\FacebookPixel\ViewModel\Config
 */
$_helper = $block->getData('config');
?>
<?php if ($_helper->getIsActive()): ?>
    <script>
        requirejs(['jquery', 'domReady'], function (domReady) {
            domReady(function () {
                <?php $items = [];
                foreach ($block->getQuote()->getAllVisibleItems() as $index => $item):
                    $items[] = [
                        'content_id' => $item->getSku(),
                        'content_name' => $item->getName(),
                        'price' => $item->getPrice(),
                        'quantity' => $item->getQty(),
                        'index' => $index + 1,
                    ];
                endforeach; ?>
                fbq('track', 'InitiateCheckout', {
                    "currency": "EUR",
                    "value": '<?= /* @noEscape */ $block->getQuote()->getSubtotal() ?>',
                    "num_items": '<?= /* @noEscape */  $block->getItemsSummaryQty(); ?>',
                    "contents": <?= /* @noEscape */ json_encode($items) ?>
                });
            });
        });
    </script>
<?php endif; ?>
