<?php
/**
 * @var $block Spirit\FacebookPixel\Block\Success
 * @var $_helper Spirit\FacebookPixel\ViewModel\Config
 */
$_helper = $block->getData('config');
?>
<?php if ($_helper->getIsActive() && $_helper->getIsPurchaseActive() && $block->getOrderId()): ?>
    <script type="text/javascript">
        requirejs(['jquery', 'domReady'], function (domReady) {
            domReady(function () {
                <?php $items = [];
                foreach ($block->getItems() as $index => $item):
                    $items[] = [
                        'content_id' => $item->getSku(),
                        'content_name' => $item->getName(),
                        'price' => $item->getPrice(),
                        'quantity' => $item->getQtyOrdered(),
                        'index' => $index + 1,
                    ];
                endforeach; ?>
                fbq('track', 'Purchase', {
                    "transaction_id": "<?= /* @noEscape */ /* @noEscape */ $block->getOrderId(); ?>",
                    "currency": "EUR",
                    "num_items": '<?= /* @noEscape */  $block->getSuccessItemsCount(); ?>',
                    "content_type": 'product',
                    "value": '<?= /* @noEscape */ /* @noEscape */ $block->getTotal() ?>',
                    "contents": <?= /* @noEscape */ json_encode($items) ?>
                });
            });
        });
    </script>
<?php endif; ?>
