<?php
/* @var $block Magento\Catalog\Block\Product\View */

$product = $block->getProduct();
?>
<script>
    requirejs(['jquery', 'domReady'], function (domReady) {
        domReady(function () {
            fbq('track', 'ViewContent', {
                "value": '<?= $product->getFinalPrice() ?>',
                "currency": "EUR",
                "content_ids": '<?= $product->getSku() ?>',
                "content_name": '<?= htmlentities($product->getName()) ?>',
                "content_type": 'product',
                //"content_category": '<?//= $product->getCategory()->getName() ?>//',
            });
        });
    });
</script>

