<?php
/**
 * @var $block Spirit\FacebookPixel\Block\ListView
 * @var $_helper Spirit\FacebookPixel\ViewModel\Config
 */
$_helper = $block->getData('config');
$jsonProducts = $block->getJsonProductCollection(); ?>
<?php if ($_helper->getIsActive() && $_helper->getIsViewCategoryActive()): ?>
    <script>
        requirejs(['jquery', 'domReady'], function (domReady) {
            domReady(function () {
                fbq('track', 'ViewCategory', {
                    "contents": <?= /* @noEscape */ $jsonProducts; ?>
                });
            });
        });
    </script>
<?php endif; ?>
